# Generated by Django 5.2.4 on 2026-02-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_created_at_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bpl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rural',
            field=models.BooleanField(default=False),
        ),
    ]
