# Generated by Django 6.0.2 on 2026-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ministry', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Farmers', 'Farmers'), ('General', 'General'), ('Women', 'Women'), ('Students', 'Students'), ('BPL', 'BPL')], max_length=50)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
