# Generated by Django 5.2.4 on 2026-02-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_id_alter_userdocument_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
