# Generated by Django 5.2.4 on 2026-02-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('identity', 'Identity Documents'), ('income', 'Income Proof'), ('other', 'Other Documents'), ('residence', 'Residence Proof'), ('education', 'Education Documents')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
