# Generated by Django 5.2.4 on 2026-02-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_category_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('identity', 'Identity Documents'), ('income', 'Income Proof'), ('other', 'Other Documents'), ('residence', 'Residence Proof'), ('education', 'Education Documents')], default='other', max_length=20),
            preserve_default=False,
        ),
    ]
