# Generated by Django 6.0.2 on 2026-02-05 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('operator', models.CharField(choices=[('<=', '<='), ('>=', '>='), ('IN', 'IN')], max_length=5)),
                ('value', models.JSONField()),
                ('message', models.CharField(max_length=255)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.scheme')),
            ],
        ),
    ]
