# Generated by Django 5.2.4 on 2026-02-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_eligibilityrule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityrule',
            name='field_name',
            field=models.CharField(help_text="Profile field name (age, annual_income, category, education_level) or 'document'", max_length=50),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='value',
            field=models.JSONField(help_text='For document rules use list of document names. For others use value or list.'),
        ),
    ]
