# Generated by Django 5.2.4 on 2026-02-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_alter_eligibilityrule_field_name_and_more'),
        ('schemes', '0002_alter_scheme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityrule',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='schemes.scheme'),
        ),
    ]
