# Generated by Django 5.2.4 on 2026-02-10 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ministry', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('BPL', 'BPL'), ('Women', 'Women'), ('Students', 'Students'), ('Farmers', 'Farmers'), ('Youth', 'Youth')], default='General', max_length=50)),
                ('target_group', models.CharField(blank=True, max_length=100)),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='eligibility.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(max_length=100)),
                ('caste_status', models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='GENERAL', max_length=10)),
                ('is_bpl', models.BooleanField(default=False)),
                ('is_farmer', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_woman', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
