# Generated by Django 5.2.4 on 2026-02-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='scheme_category',
            field=models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Employment', 'Employment'), ('Housing', 'Housing'), ('Finance', 'Finance'), ('Women & Child', 'Women & Child'), ('Agriculture', 'Agriculture'), ('Social Welfare', 'Social Welfare')], default='General', max_length=50),
        ),
    ]
